import Link from "next/link";
import { AnimatedHero } from "@/components/animated-hero";
import { Footer } from "@/components/footer";
import { Reveal } from "@/components/motion/reveal";
import { ProjectArtwork } from "@/components/project-artwork";
import { SiteHeader } from "@/components/site-header";
import { experience, skills } from "@/data/profile";
import { featuredProjects } from "@/data/projects";

export default function FrenchHomePage() {
  return <main><SiteHeader locale="fr" /><AnimatedHero locale="fr" /><section className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-16" id="work"><Reveal><p className="eyebrow">Projets sélectionnés</p><h2 className="section-title mt-4">De grandes questions transformées en systèmes concrets.</h2></Reveal><div className="work-mosaic mt-14">{featuredProjects.map((project, index) => <Reveal delay={index * 0.08} key={project.slug}><Link className={`work-card work-card-${index} group`} href={`/work/${project.slug}`}><ProjectArtwork project={project} variant={index} /><p className="eyebrow mt-5">{project.category}</p><h3 className="mt-2 font-serif text-3xl">{project.title}</h3><p className="mt-3 leading-7 text-[#674854]">{project.summary}</p></Link></Reveal>)}</div></section><section className="skills-band py-24" id="skills"><div className="mx-auto max-w-7xl px-6 sm:px-10 lg:px-16"><Reveal><p className="eyebrow">Compétences</p><h2 className="mt-4 max-w-3xl font-serif text-4xl leading-tight sm:text-5xl">Un socle technique entre recherche et produit.</h2><div className="mt-10 flex flex-wrap gap-2">{skills.flatMap((skill) => skill.items).map((skill) => <span className="skill-chip" key={skill}>{skill}</span>)}</div></Reveal></div></section><section className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-16" id="experience"><Reveal><p className="eyebrow">Expérience</p><h2 className="section-title mt-4">Transformer les expérimentations en pratique fiable.</h2></Reveal><div className="mt-10 experience-stack">{experience.map((item, index) => <Reveal delay={index * 0.08} key={item.organization}><article className="experience-row"><p className="font-mono text-xs text-[#bf4d80]">0{index + 1} / {item.year}</p><div><h3 className="font-serif text-2xl">{item.role}</h3><p className="mt-1 font-medium">{item.organization}</p><p className="mt-3 leading-7 text-[#674854]">{item.focus.join(" · ")}</p></div></article></Reveal>)}</div></section><Footer locale="fr" /></main>;
}
