import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer } from "@/components/footer";
import { ProjectArtwork } from "@/components/project-artwork";
import { SiteHeader } from "@/components/site-header";
import { getProject, projects } from "@/data/projects";

export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: PageProps<"/work/[slug]">): Promise<Metadata> { const { slug } = await params; const project = getProject(slug); return project ? { title: `${project.title} | Zouhour Bellamine`, description: project.summary } : {}; }
export default async function ProjectPage({ params }: PageProps<"/work/[slug]">) { const { slug } = await params; const project = getProject(slug); if (!project) notFound(); return <main><SiteHeader /><article><section className="mx-auto max-w-7xl px-6 pb-16 pt-14 sm:px-10 lg:px-16"><Link className="text-link" href="/work">← All work</Link><p className="eyebrow mt-12">{project.category}</p><h1 className="mt-5 max-w-5xl font-serif text-5xl leading-[0.98] sm:text-7xl">{project.title}</h1><p className="mt-7 max-w-3xl text-xl leading-8 text-[#5f4650]">{project.summary}</p></section><div className="mx-auto max-w-7xl px-6 sm:px-10 lg:px-16"><ProjectArtwork project={project} variant={projects.indexOf(project)} /></div><section className="mx-auto grid max-w-7xl gap-12 px-6 py-24 sm:px-10 lg:grid-cols-[0.8fr_1.2fr] lg:px-16"><div><p className="eyebrow">Overview</p></div><div className="space-y-14"><CaseSection title="Problem"><p>{project.problem}</p></CaseSection><CaseSection title="Approach"><p>{project.approach}</p></CaseSection><CaseSection title="Architecture"><ol className="architecture-list">{project.architecture.map((part, index) => <li key={part}><span>0{index + 1}</span>{part}</li>)}</ol></CaseSection><CaseSection title="Engineering decisions"><ul className="case-list">{project.decisions.map((item) => <li key={item}>{item}</li>)}</ul></CaseSection><CaseSection title="Challenges"><ul className="case-list">{project.challenges.map((item) => <li key={item}>{item}</li>)}</ul></CaseSection><CaseSection title="Current status"><p>{project.status}</p></CaseSection><CaseSection title="Technologies"><div className="flex flex-wrap gap-2">{project.technologies.map((technology) => <span className="tag" key={technology}>{technology}</span>)}</div></CaseSection><div className="border-t border-[#e8bdcb] pt-6"><p className="font-mono text-xs uppercase tracking-[0.14em] text-[#a63d70]">Links</p><p className="mt-3 leading-7 text-[#5f4650]">Repository and demo links will be added when they can be shared.</p></div></div></section></article><Footer /></main>; }
function CaseSection({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="font-serif text-3xl">{title}</h2><div className="mt-4 max-w-2xl leading-8 text-[#5f4650]">{children}</div></section>; }
