import Link from "next/link";
import { AnimatedHero } from "@/components/animated-hero";
import { EditorialProject } from "@/components/editorial-project";
import { Footer } from "@/components/footer";
import { JourneyTimeline } from "@/components/journey-timeline";
import { Reveal } from "@/components/motion/reveal";
import { PersonalitySection } from "@/components/personality-section";
import { SiteHeader } from "@/components/site-header";
import { SkillExplorer } from "@/components/skill-explorer";
import { projects } from "@/data/projects";

export default function Home() {
  const copilot = projects.find((project) => project.slug === "ai-research-copilot")!;
  const spark = projects.find((project) => project.slug === "spark-ai")!;
  const moreProjects = projects.filter((project) => project !== copilot && project !== spark);
  return <main><SiteHeader /><AnimatedHero /><section className="identity-band"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-24 sm:px-10 lg:grid-cols-[.78fr_1.22fr] lg:px-16"><Reveal><p className="eyebrow">A practice in progress</p><p className="identity-quote">I am drawn to the point where a difficult question becomes a system someone can actually use.</p></Reveal><Reveal delay={0.12}><div className="identity-copy"><p>My path through ENET&apos;Com gave me a systems perspective: data, decisions, and software belong together. Since then, I have been building at the intersection of research, product thinking, and careful engineering.</p><Link className="text-link" href="/about">More about the person behind the work <span aria-hidden="true">↗</span></Link></div></Reveal></div></section><section className="project-led" id="work"><div className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-16"><Reveal><div className="section-heading"><div><p className="eyebrow">Selected systems</p><h2>Work that makes intelligence tangible.</h2></div><p>Two projects at the centre of my practice: one turns research into a traceable conversation, the other turns product images into a generative marketing workflow.</p></div></Reveal><div className="editorial-projects"><EditorialProject number="01" project={copilot} /><EditorialProject number="02" project={spark} /></div></div></section><section className="project-constellation"><div className="mx-auto max-w-7xl px-6 py-24 sm:px-10 lg:px-16"><div className="constellation-heading"><p className="eyebrow">More evidence</p><Link className="text-link" href="/work">See the complete work archive <span aria-hidden="true">↗</span></Link></div><div className="constellation-grid">{moreProjects.map((project, index) => <Link className="constellation-project" href={`/work/${project.slug}`} key={project.slug}><span>0{index + 3}</span><h3>{project.title}</h3><p>{project.category}</p><i aria-hidden="true">↗</i></Link>)}</div></div></section><section className="journey-band"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-24 sm:px-10 lg:grid-cols-[.78fr_1.22fr] lg:px-16"><Reveal><div><p className="eyebrow">The through-line</p><h2 className="section-title mt-4">A career built by following the useful problems.</h2></div></Reveal><Reveal delay={0.12}><JourneyTimeline compact /></Reveal></div></section><section className="skills-band py-24"><div className="mx-auto grid max-w-7xl gap-12 px-6 sm:px-10 lg:grid-cols-[0.8fr_1.2fr] lg:px-16"><Reveal><div><p className="eyebrow">Technical ecosystem</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">A compact map of the tools behind the work.</h2><p className="mt-6 max-w-md leading-8 text-[#f9e9ef]">The stack is not a checklist. It is a set of choices shaped by the systems above.</p></div></Reveal><Reveal delay={0.12}><SkillExplorer /></Reveal></div></section><PersonalitySection /><Footer /></main>;
}
