import Link from "next/link";
import { ContactForm } from "@/components/contact-form";
import { contact } from "@/data/profile";
import { SocialSignature } from "@/components/social-signature";

export function Footer({ locale = "en" }: { locale?: "en" | "fr" }) {
  const fr = locale === "fr";
  const copy = fr ? { heading: "Construisons une idée qui compte.", intro: "Disponible pour des opportunités junior en IA, logiciel, machine learning et data engineering.", label: "Me contacter", location: "Monastir, Tunisie", download: "Télécharger le CV", top: "Retour en haut" } : { heading: "Let's make the next idea feel possible.", intro: "Open to junior opportunities in AI engineering, software engineering, machine learning, and data engineering.", label: "Get in touch", location: contact.location, download: "Download CV", top: "Back to top" };
  return <footer className="contact-footer" id="contact"><div className="contact-grid mx-auto max-w-7xl px-6 py-20 sm:px-10 lg:px-16"><div><p className="eyebrow">{copy.label}</p><h2 className="mt-4 max-w-xl font-serif text-5xl leading-[.95] sm:text-6xl">{copy.heading}</h2><p className="mt-7 max-w-xl text-lg leading-8 text-[#6b4b59]">{copy.intro}</p><div className="mt-9 space-y-2 text-sm text-[#6b4b59]"><p>{copy.location}</p><p>{contact.phone}</p><a className="text-link" href={`mailto:${contact.email}`}>{contact.email}</a></div><div className="contact-links mt-9"><a aria-label="Zouhour on LinkedIn" className="contact-icon" href={contact.linkedin} rel="noreferrer" target="_blank">in</a><a aria-label="Zouhour on GitHub" className="contact-icon" href={contact.github} rel="noreferrer" target="_blank">GH</a><a aria-label="Zouhour on Medium" className="contact-icon contact-medium" href={contact.medium} rel="noreferrer" target="_blank">M</a></div><a className="cv-footer-link mt-8 inline-flex" download href="/cv/zouhour-bellamine-cv-en.pdf">{copy.download} <span aria-hidden="true">↓</span></a></div><ContactForm locale={locale} /></div><SocialSignature /><div className="mx-auto flex max-w-7xl justify-between border-t border-[#e8bdcb] px-6 py-5 text-sm text-[#5f4650] sm:px-10 lg:px-16"><span>© {new Date().getFullYear()} Zouhour Bellamine</span><Link className="nav-link" href={fr ? "/fr" : "/"}>{copy.top}</Link></div></footer>;
}
